// <auto-generated />
using System;
using FactoryGame.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FactoryGame.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510185850_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.EconomyTransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CashDelta")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("EconomyTransactions");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.InventoryPoolEntity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<long>("MaxVolume")
                        .HasColumnType("bigint");

                    b.Property<long>("UsedVolume")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId");

                    b.ToTable("InventoryPools");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerBalanceEntity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cash")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerBalances");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuestDeviceKeyHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuestDeviceKeyHash")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerSessionEntity", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Token");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerSessions");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PoolStackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ElementId")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<long>("VolumePerUnit")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "ElementId")
                        .IsUnique();

                    b.ToTable("PoolStacks");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.InventoryPoolEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", "Player")
                        .WithOne("Pool")
                        .HasForeignKey("FactoryGame.Infrastructure.Data.Entities.InventoryPoolEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerBalanceEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", "Player")
                        .WithOne("Balance")
                        .HasForeignKey("FactoryGame.Infrastructure.Data.Entities.PlayerBalanceEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerSessionEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PoolStackEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.InventoryPoolEntity", "Pool")
                        .WithMany("Stacks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pool");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.InventoryPoolEntity", b =>
                {
                    b.Navigation("Stacks");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", b =>
                {
                    b.Navigation("Balance")
                        .IsRequired();

                    b.Navigation("Pool")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
