// <auto-generated />
using System;
using FactoryGame.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FactoryGame.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510190524_ApiKeysForeignKeyToPlayer")]
    partial class ApiKeysForeignKeyToPlayer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.ApiKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("PlayerId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.BoardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LastSnapshotNote")
                        .HasColumnType("text");

                    b.Property<byte>("Mode")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("RevisionVersion")
                        .HasColumnType("integer");

                    b.Property<long>("SimulationTick")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.BoardRevisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "Version")
                        .IsUnique();

                    b.ToTable("BoardRevisions");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.EconomyTransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CashDelta")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("EconomyTransactions");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.InventoryPoolEntity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<long>("MaxVolume")
                        .HasColumnType("bigint");

                    b.Property<long>("UsedVolume")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId");

                    b.ToTable("InventoryPools");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.MarketOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ElementId")
                        .HasColumnType("integer");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text");

                    b.Property<decimal?>("LimitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<long>("OriginalQuantity")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<long>("QuantityRemaining")
                        .HasColumnType("bigint");

                    b.Property<byte>("Side")
                        .HasColumnType("smallint");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ElementId", "Status", "Side");

                    b.ToTable("MarketOrders");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerBalanceEntity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cash")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerBalances");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuestDeviceKeyHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuestDeviceKeyHash")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerSessionEntity", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Token");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerSessions");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PoolStackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ElementId")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<long>("VolumePerUnit")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "ElementId")
                        .IsUnique();

                    b.ToTable("PoolStacks");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.SimulationClockEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("CurrentTick")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastAdvancedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SimulationClock");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.TradeExecutionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerPlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ElementId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SellOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SellerPlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.ToTable("TradeExecutions");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.ApiKeyEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.BoardEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.BoardRevisionEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.BoardEntity", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.InventoryPoolEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", "Player")
                        .WithOne("Pool")
                        .HasForeignKey("FactoryGame.Infrastructure.Data.Entities.InventoryPoolEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerBalanceEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", "Player")
                        .WithOne("Balance")
                        .HasForeignKey("FactoryGame.Infrastructure.Data.Entities.PlayerBalanceEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerSessionEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PoolStackEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.InventoryPoolEntity", "Pool")
                        .WithMany("Stacks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pool");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.InventoryPoolEntity", b =>
                {
                    b.Navigation("Stacks");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", b =>
                {
                    b.Navigation("Balance")
                        .IsRequired();

                    b.Navigation("Pool")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
