// <auto-generated />
using System;
using FactoryGame.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FactoryGame.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.ApiKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("PlayerId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.BoardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastSnapshotNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Mode")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RevisionVersion")
                        .HasColumnType("int");

                    b.Property<long>("SimulationTick")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.BoardKeyframeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LineStateJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RevisionVersion")
                        .HasColumnType("int");

                    b.Property<string>("SeaportDeltaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Tick")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "Tick");

                    b.ToTable("BoardKeyframes");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.BoardRevisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "Version")
                        .IsUnique();

                    b.ToTable("BoardRevisions");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.EconomyTransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CashDelta")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("EconomyTransactions");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.InventoryPoolEntity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("MaxVolume")
                        .HasColumnType("bigint");

                    b.Property<long>("UsedVolume")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId");

                    b.ToTable("InventoryPools");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.MarketOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Dna")
                        .HasColumnType("bigint");

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LimitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("OriginalQuantity")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("QuantityRemaining")
                        .HasColumnType("bigint");

                    b.Property<byte>("Side")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("SponsorCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("SponsorCompanyId");

                    b.HasIndex("PlayerId", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("ElementId", "Dna", "IsSynthetic", "Status");

                    b.HasIndex("ElementId", "Dna", "Status", "Side");

                    b.ToTable("MarketOrders");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.MarketPriceCandleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("BucketStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ElementId", "BucketStart")
                        .IsUnique();

                    b.ToTable("MarketPriceCandles", (string)null);
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerBalanceEntity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cash")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerBalances");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GuestDeviceKeyHash")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsSponsorAccount")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GuestDeviceKeyHash")
                        .IsUnique()
                        .HasFilter("[GuestDeviceKeyHash] IS NOT NULL");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerMachineStockEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MachineType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerMachineStocks");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerSessionEntity", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Token");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerSessions");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PoolStackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Dna")
                        .HasColumnType("bigint");

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<long>("VolumePerUnit")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "ElementId", "Dna")
                        .IsUnique();

                    b.ToTable("PoolStacks");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.SimulationClockEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<long>("CurrentTick")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastAdvancedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("SimulationClock");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.SponsorCompanyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BudgetRemaining")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExposureTier")
                        .HasColumnType("int");

                    b.Property<int>("FundingMode")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TotalBudget")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("VirtualSpend")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("SponsorCompanies");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.SponsorCompanyOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Dna")
                        .HasColumnType("bigint");

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("LimitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("LinkedMarketOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Side")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("SponsorCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TargetQuantity")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SponsorCompanyId", "IsActive");

                    b.ToTable("SponsorCompanyOrders");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.TradeExecutionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BuyerSponsorCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Dna")
                        .HasColumnType("bigint");

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SellOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SellerPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SellerSponsorCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BuyerSponsorCompanyId");

                    b.HasIndex("SellerSponsorCompanyId");

                    b.HasIndex("ElementId", "Dna");

                    b.HasIndex("ElementId", "Dna", "CreatedAt");

                    b.ToTable("TradeExecutions");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.ApiKeyEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.BoardEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.BoardKeyframeEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.BoardEntity", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.BoardRevisionEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.BoardEntity", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.InventoryPoolEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", "Player")
                        .WithOne("Pool")
                        .HasForeignKey("FactoryGame.Infrastructure.Data.Entities.InventoryPoolEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerBalanceEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", "Player")
                        .WithOne("Balance")
                        .HasForeignKey("FactoryGame.Infrastructure.Data.Entities.PlayerBalanceEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerMachineStockEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerSessionEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PoolStackEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.InventoryPoolEntity", "Pool")
                        .WithMany("Stacks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pool");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.SponsorCompanyEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.SponsorCompanyOrderEntity", b =>
                {
                    b.HasOne("FactoryGame.Infrastructure.Data.Entities.SponsorCompanyEntity", "SponsorCompany")
                        .WithMany("StandingOrders")
                        .HasForeignKey("SponsorCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SponsorCompany");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.InventoryPoolEntity", b =>
                {
                    b.Navigation("Stacks");
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.PlayerEntity", b =>
                {
                    b.Navigation("Balance")
                        .IsRequired();

                    b.Navigation("Pool")
                        .IsRequired();
                });

            modelBuilder.Entity("FactoryGame.Infrastructure.Data.Entities.SponsorCompanyEntity", b =>
                {
                    b.Navigation("StandingOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
